/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.takzok.kafka.streams;

import org.junit.Test;

public class TransformTest {
    @Test public void testAppHasAGreeting() {
    }
}
