version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    volumes:
      - ./volume/zookeeper/:/var/run/docker.sock
  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:9092,INSIDE://:9192
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://127.0.0.1:9092,INSIDE://_{HOSTNAME_COMMAND}:9192
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "TextLines:1:1,WordWithCounts:1:1"
    volumes:
      - ./volume/kafka/:/var/run/docker.sock
  postgres:
    image: postgres:11.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "./volume/postgres/initdb:/docker-entrypoint-initdb.d"
